version: "3.8"
services:
  postgres_service:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
  pgadmin_service:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    ports:
      - "5050:80"
volumes:
  postgres_volume:
  pgadmin_volume:
